### ISSUE TITLE
Set to show above submit button

### ISSUE THREAD

**Issue by kamauwanjoroge** [WPJohnny-plugins/comment-reply-email#1]
1. Is it possible to set the box to show above the submit button?
2. Is this plugin pure PHP or it has JS?

**Comment by wpjohnny** [comment]
1. That's a great idea. I'll see how easy that is. I liked below because it stood out but I can see why some people want to avoid an extra line sticking out. I don't have an easy filter right now but will consider it.
2. It's pure PHP. No JS as I would hate that to death.

**Comment by kamauwanjoroge** [comment]
1. Thanks. When you create a filter, give it a priority so that it appears before or just after the other checkbox by WP requiring to save users details if possible. I will install the plugin after this option is incorporated to keep up with my site design.
2. Good to know. I moved away from using jQuery on the frontend and only rely on vanilla js.

**Comment by wpjohnny** [comment]
Got it. Will keep this in mind for next update.

**Comment by kamauwanjoroge** [comment]
@wpjohnny not to pressure you or anything but:
1. Do you have an ETA for this update?
2. Does the plugin subscribe the users to their replies only or to both new comments and replies? I would prefer the former.

**Comment by wpjohnny** [comment]
1. I don?t know. Could be today, could be 3 months. It?s not priority right now but I?ll poke in there when I get a chance.2. Mine does only the former.

**Comment by lopwalj** [comment]
@askel45 actually, it's possible to show the subscribe box above the submit button (when logged in) but note WordPress doesn't offer a hook between the input fields (name, email, comment) and the submit button when you are logged in, so the checkbox can only be displayed above the comment field.

Do you have knowledge how to manipulate hooked functions within a class object?
This snipped should give you what you need:
`add_action( 'wp_head', function() {
	// Check if comment_reply_email class exists.
	if ( class_exists( 'comment_reply_email' ) ) :

		// Access to the class object instance
		global $comment_reply_email;

		// Remove the action
		remove_action( 'comment_form', array( $comment_reply_email, 'addreplyidformfield' ), 9999 );

		// Hook the action in different hooks based on user log state
		if ( is_user_logged_in() ) :
			add_action( 'comment_form_logged_in_after', array( $comment_reply_email, 'addreplyidformfield' ) );
		else:
			add_action( 'comment_form_after_fields', array( $comment_reply_email, 'addreplyidformfield' ) );
		endif;

	endif;
});`

**Comment by lopwalj** [comment]
@askel45 actually, it's possible to show the subscribe box above the submit button (when logged in) but note WordPress doesn't offer a hook between the input fields (name, email, comment) and the submit button when you are logged in, so the checkbox can only be displayed above the comment field.

Do you have knowledge how to manipulate hooked functions within a class object?
This snipped should give you what you need:
`add_action( 'wp_head', function() {
	// Check if comment_reply_email class exists.
	if ( class_exists( 'comment_reply_email' ) ) :

		// Access to the class object instance
		global $comment_reply_email;

		// Remove the action
		remove_action( 'comment_form', array( $comment_reply_email, 'addreplyidformfield' ), 9999 );

		// Hook the action in different hooks based on user log state
		if ( is_user_logged_in() ) :
			add_action( 'comment_form_logged_in_after', array( $comment_reply_email, 'addreplyidformfield' ) );
		else:
			add_action( 'comment_form_after_fields', array( $comment_reply_email, 'addreplyidformfield' ) );
		endif;

	endif;
});`

**Comment by wpjohnny** [comment]
@askel45 actually, it's possible to show the subscribe box above the submit button (when logged in) but note WordPress doesn't offer a hook between the input fields (name, email, comment) and the submit button when you are logged in, so the checkbox can only be displayed above the comment field.

Do you have knowledge how to manipulate hooked functions within a class object?

This snipped should give you what you need:
```
add_action( 'wp_head', function() {
// Check if comment_reply_email class exists.
if ( class_exists( 'comment_reply_email' ) ) :
	// Access to the class object instance
	global $comment_reply_email;

	// Remove the action
	remove_action( 'comment_form', array( $comment_reply_email, 'addreplyidformfield' ), 9999 );

	// Hook the action in different hooks based on user log state
	if ( is_user_logged_in() ) :
		add_action( 'comment_form_logged_in_after', array( $comment_reply_email, 'addreplyidformfield' ) );
	else:
		add_action( 'comment_form_after_fields', array( $comment_reply_email, 'addreplyidformfield' ) );
	endif;

endif;

});
```

**Comment by kamauwanjoroge** [comment]
It worked but styling it is a bit difficult coz the output 'p' tag has no class in it. I use a different font size for the checkboxes and the labels. I had to edit the plugin itself.

**Comment by wpjohnny** [comment]
You can't use the ID?

Johnny Nguyen
WordPress Speed Expert
johnny@wpjohnny.com (https://link.getmailspring.com/link/7E336D8D-AB4A-4194-B42C-6D75AB8BB9DA@getmailspring.com/0?redirect=mailto%3Ajohnny%40wpjohnny.com&recipient=cmVwbHkrQUtNUDZMRlpaUDNWQkpRNVo1SUxZQTU1SVdUV1RFVkJOSEhDUTQ2TVJVQHJlcGx5LmdpdGh1Yi5jb20%3D)
https://wpjohnny.com (https://link.getmailspring.com/link/7E336D8D-AB4A-4194-B42C-6D75AB8BB9DA@getmailspring.com/1?redirect=https%3A%2F%2Fwpjohnny.com&recipient=cmVwbHkrQUtNUDZMRlpaUDNWQkpRNVo1SUxZQTU1SVdUV1RFVkJOSEhDUTQ2TVJVQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by wpjohnny** [comment]
Actually sorry, I see it. There's nothing set overall. Ok...back to the code!

Johnny Nguyen
WordPress Speed Expert
johnny@wpjohnny.com (https://link.getmailspring.com/link/5B521313-0F82-4A43-85D2-908CDB2A9256@getmailspring.com/0?redirect=mailto%3Ajohnny%40wpjohnny.com&recipient=cmVwbHkrQUtNUDZMRlpaUDNWQkpRNVo1SUxZQTU1SVdUV1RFVkJOSEhDUTQ2TVJVQHJlcGx5LmdpdGh1Yi5jb20%3D)
https://wpjohnny.com (https://link.getmailspring.com/link/5B521313-0F82-4A43-85D2-908CDB2A9256@getmailspring.com/1?redirect=https%3A%2F%2Fwpjohnny.com&recipient=cmVwbHkrQUtNUDZMRlpaUDNWQkpRNVo1SUxZQTU1SVdUV1RFVkJOSEhDUTQ2TVJVQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by kamauwanjoroge** [comment]
> Actually sorry, I see it. There's nothing set overall. Ok...back to the code!

I don't understand what you mean here...

**Comment by wpjohnny** [comment]
Just meant that we have to code it in to make it accessible for you.

**Comment by kamauwanjoroge** [comment]
> Just meant that we have to code it in to make it accessible for you.

Makes sense. If possible, add an ID or class to the P section and the two inner sections (checkbox and text).
